__version__:
  serializer: 1
  data: 8
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 2
        Brightness: 1.8
        ExposureTime: 3354
        Gain: 1.50180044068462
    - Acquisition:
        Aperture: 3.54013439916361
        Brightness: 1.8
        ExposureTime: 1677
        Gain: 1.00467354849355
  Experimental:
    Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Experimental:
        ToneMapping:
          Enabled: always
      Gamma: 1
    Filters:
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.3
          Removal:
            Enabled: no
            Threshold: 0.2
      Noise:
        Removal:
          Enabled: yes
          Threshold: 5
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 10
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1
